<a href="https://colab.research.google.com/github/jackaquamin/myprojects/blob/main/SingleNeuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# input
x = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
print(x)

# check the shape of input
print('The shape of x is :',x.shape)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
The shape of x is : (4, 3)


In [ ]:
# output data
y=np.array([[0],[1],[1],[1]])
print(y)
print('The shape of y is :',y.shape)

[[0]
 [1]
 [1]
 [1]]
The shape of y is : (4, 1)


In [ ]:
#random weights
np.random.seed(1)
w=np.random.random((3,1))
print('Random weights: ',w)

Random weights:  [[4.17022005e-01]
 [7.20324493e-01]
 [1.14374817e-04]]


In [ ]:
#feed forward
input = x
weighted_sum = (np.dot(x,w))
print(weighted_sum)

[[1.14374817e-04]
 [7.20438868e-01]
 [4.17136380e-01]
 [1.13746087e+00]]


In [ ]:
#sigmoid activation function
activated_output = 1/(1+np.exp(-weighted_sum))
print('Activated Output',activated_output)

Activated Output [[0.50002859]
 [0.67270365]
 [0.60279781]
 [0.75721315]]


In [ ]:
#calculate the error
error = y-activated_output
print('The errors are: ',error)

The errors are:  [[-0.50002859]
 [ 0.32729635]
 [ 0.39720219]
 [ 0.24278685]]


In [ ]:
tot_error = np.mean(np.abs(error))
print('Total error: ',tot_error)

Total error:  0.3668284967341482


In [ ]:
#backpropagation (Tune the weights)
#using derivatate of sigmoid
 
for j in range(1000):
  input = x
  weighted_sum = (np.dot(x,w))
  activated_output = 1/ (1+ np.exp(-weighted_sum))  # sigmoid function
  error = y - activated_output
  print ("Average error : ", np.mean(np.abs(error)))

  # tune the weights
  d_w = error * ( 1/ (1+ np.exp(-activated_output)) * (1- 1/ (1+ np.exp(-activated_output))))
  w += x.T.dot(d_w)

Average error :  0.003275883007779243
Average error :  0.003274823882718861
Average error :  0.003273765440833771
Average error :  0.0032727076814638555
Average error :  0.0032716506039502527
Average error :  0.0032705942076348016
Average error :  0.0032695384918599853
Average error :  0.0032684834559696205
Average error :  0.003267429099307948
Average error :  0.0032663754212201804
Average error :  0.0032653224210523408
Average error :  0.0032642700981513942
Average error :  0.0032632184518650307
Average error :  0.003262167481541828
Average error :  0.0032611171865311963
Average error :  0.0032600675661832957
Average error :  0.0032590186198493123
Average error :  0.0032579703468811755
Average error :  0.003256922746631371
Average error :  0.003255875818453795
Average error :  0.0032548295617025893
Average error :  0.0032537839757330843
Average error :  0.0032527390599011883
Average error :  0.0032516948135639413
Average error :  0.003250651236078904
Average error :  0.00324960832680